# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - freewebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'freewebapp'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE publishData><publishProfile profileName="freewebapp - Web Deploy" publishMethod="MSDeploy" publishUrl="freewebapp-dzd8egdhe8d7b7ez.scm.southafricanorth-01.azurewebsites.net:443" msdeploySite="freewebapp" userName="$freewebapp" userPWD="sL2xNBsj5TGWfu2cFWbqFvWbFDLBLNmXMzdQnjS9kTw4oQ8sfP35i9sC4bRp" destinationAppUrl="https://freewebapp-dzd8egdhe8d7b7ez.southafricanorth-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="freewebapp - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-jnb21-019.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="REDACTED" userPWD="REDACTED" destinationAppUrl="https://freewebapp-dzd8egdhe8d7b7ez.southafricanorth-01.azurewebsites.net" SQLServerDBConnectionString="REDACTED" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="freewebapp - Zip Deploy" publishMethod="ZipDeploy" publishUrl="freewebapp-dzd8egdhe8d7b7ez.scm.southafricanorth-01.azurewebsites.net:443" userName="$freewebapp" userPWD="sL2xNBsj5TGWfu2cFWbqFvWbFDLBLNmXMzdQnjS9kTw4oQ8sfP35i9sC4bRp" destinationAppUrl="https://freewebapp-dzd8egdhe8d7b7ez.southafricanorth-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData> }}
